# Generated by Django 6.0.5 on 2026-05-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("options", models.JSONField()),
                ("correct_answer", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("difficulty", models.CharField(max_length=50)),
                ("interview_type", models.CharField(max_length=100)),
            ],
        ),
    ]
