# Generated by Django 6.0.5 on 2026-06-15 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_assessmentresult"),
        ("interviews", "0007_question_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_questions",
                to="interviews.interview",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
    ]
