# Generated by Django 6.0.5 on 2026-05-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.IntegerField()),
                ("communication_score", models.IntegerField()),
                ("technical_score", models.IntegerField()),
                ("strengths", models.TextField()),
                ("weaknesses", models.TextField()),
                ("recommendation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="interviews.interview",
                    ),
                ),
            ],
        ),
    ]
