# Generated by Django 6.0.5 on 2026-05-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0004_interviewfeedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InterviewFeedback",
        ),
    ]
