# Generated by Django 6.0.5 on 2026-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0005_delete_interviewfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
    ]
