# Generated by Django 6.0.5 on 2026-06-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0006_question_is_ai_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_questions",
                to="interviews.interview",
            ),
        ),
    ]
