# Generated by Django 6.0.5 on 2026-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0007_question_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
